'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const required = ['index.html', 'styles.css', 'app.js', 'data.json', 'README.md', '.gitignore', 'assets/oren-mizrah-logo.jpg', 'assets/altshuler-logo.jpg'];
required.forEach(file => assert.ok(fs.existsSync(path.join(root, file)), `Missing ${file}`));
const data = JSON.parse(fs.readFileSync(path.join(root, 'data.json'), 'utf8'));
assert.equal(data.campaign.title, '250 מיליון לאלטשולר שחם');
assert.equal(data.campaign.target, 250000000);
assert.equal(data.campaign.currency, 'ILS');
assert.equal(data.campaign.deadline, '2026-12-31');
assert.equal(data.campaign.lastUpdated, '2026-07-27T20:09:35+03:00');
assert.ok(!Number.isNaN(Date.parse(data.campaign.lastUpdated)), 'lastUpdated must be ISO-compatible');
assert.deepEqual(data.teams.map(team => team.name), ['קבוצת לירון בריל', 'קבוצת אסף אלמקייס']);
data.teams.forEach(team => {
  assert.ok(Array.isArray(team.agents), `${team.name}: agents must be an array`);
  assert.equal('total' in team, false, `${team.name}: totals must be derived, not stored`);
});
assert.equal(data.teams[0].agents.length, 0, 'Liron team must remain empty');
assert.deepEqual(data.teams[1].agents, [{ id: 'elite-agency', name: 'סוכנות עילית', sales: 900000 }]);
const globalSold = data.teams.flatMap(team => team.agents).reduce((sum, agent) => sum + agent.sales, 0);
assert.equal(globalSold, 900000, 'global sold must derive from agents');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
assert.match(html, /<html lang="he" dir="rtl">/);
assert.match(html, /<title>250 מיליון לאלטשולר שחם<\/title>/);
console.log(`✓ ${required.length} required files found`);
console.log('✓ campaign, teams, and derived-sales data schema valid');
console.log('✓ Hebrew RTL document metadata valid');
