'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const required = ['index.html', 'styles.css', 'app.js', 'data.json', 'README.md', '.gitignore', 'assets/oren-mizrah-logo.jpg', 'assets/altshuler-logo.jpg'];
required.forEach(file => assert.ok(fs.existsSync(path.join(root, file)), `Missing ${file}`));
const data = JSON.parse(fs.readFileSync(path.join(root, 'data.json'), 'utf8'));
assert.equal(data.campaign.title, 'אורן מזרח מוכרת 250M אלטשולר שחם💸');
assert.equal(data.campaign.target, 250000000);
assert.equal(data.campaign.currency, 'ILS');
assert.equal(data.campaign.deadline, '2026-12-31');
assert.ok(!Number.isNaN(Date.parse(data.campaign.lastUpdated)), 'lastUpdated must be ISO-compatible');
assert.ok(data.teams.some(team => team.id === 'liron-brill'), 'Liron team missing');
assert.ok(data.teams.some(team => team.id === 'assaf-elmakias'), 'Assaf team missing');
assert.equal(new Set(data.teams.map(team => team.id)).size, data.teams.length, 'team ids must be unique');
data.teams.forEach(team => {
  assert.ok(Array.isArray(team.agents), `${team.name}: agents must be an array`);
  assert.equal('total' in team, false, `${team.name}: totals must be derived, not stored`);
  assert.equal(typeof team.managerImage, 'string', `${team.name}: managerImage must be a string`);
  assert.equal(new Set(team.agents.map(agent => agent.id)).size, team.agents.length, `${team.name}: agent ids must be unique`);
  team.agents.forEach(agent => {
    assert.ok(agent.name, `${team.name}: agent name is required`);
    assert.ok(Number.isFinite(agent.sales) && agent.sales >= 0, `${team.name}: agent sales must be non-negative`);
  });
});
const globalSold = data.teams.flatMap(team => team.agents).reduce((sum, agent) => sum + agent.sales, 0);
assert.ok(globalSold <= data.campaign.target * 10, 'global sold is implausibly high');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
assert.match(html, /<html lang="he" dir="rtl">/);
assert.match(html, /<title>אורן מזרח מוכרת 250M אלטשולר שחם💸<\/title>/);
console.log(`✓ ${required.length} required files found`);
console.log('✓ campaign, teams, and derived-sales data schema valid');
console.log('✓ Hebrew RTL document metadata valid');
